### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Ross-Rawlins** [devnixs/ODataAngularResources#44]
How do you add a token to the gets for authentication? I am used to doing it with the $http but not with odata and this extension.

**Comment by devnixs** [comment]
You can use http [interceptors](https://docs.angularjs.org/api/ng/service/$http#interceptors) for that.

**Comment by vance** [comment]
Interceptors are great. I've also added custom headers to the http defaults, in my case I pass a bearer token for auth for all transactions:

`this.http.defaults.headers.common['Authorization'] = 'Bearer ' + result.data.data.access_token;`

this adds the default token to all $http requests, including odata (since this library just extends $resource).
