### ISSUE TITLE
ODataAngularResources cannot generate odata string

### ISSUE THREAD

**Issue by PremeraSOAPOC** [devnixs/ODataAngularResources#86]
It seems .query() will actually fire up a call to the server side.  Is there a way to generate odata string only and not fire up a call?

**Comment by kyse** [comment]
I believe you're looking for the execute method on the ODdataProvider which should return the final query string which gets appended to the url.

**Comment by alphagopher** [comment]
Thanks! This was exactly what I was looking for. Really enjoying this library so far, kudos. 

An issue I've run into using client-side OData requests for queries is that I'm now implementing a job scheduler for queries, which I've found needs to be server-side. Shamefully planning to store off these magic strings instead of porting client code to the sever.
